baseURL = "https://blog.lferraz.com"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
theme = ["github.com/onweru/compose"]
title = "Devil in (the) Details"
[outputs]
home = ["HTML", "RSS", "JSON"]
