[build]
  publish = "dist"
  command = "npm clean cache --force && yarn cache clean sharp && yarn build"
[build.processing.js]
  bundle = false
  minify = true
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
