[build]
  publish = "dist"
  command = "yarn build"
[build.processing.js]
  bundle = false
  minify = false
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
