---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: CONFIG
- type: document
  path: config.toml
  label: Settings
- type: directory
  path: config/_default
  label: Default Env
  create: all
  match: "**/*"
  new_doc_ext: toml
- type: directory
  path: config/staging
  label: Staging Env
  create: all
  match: "**/*"
  new_doc_ext: toml
- type: heading
  label: PAGES
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: directory
  path: content/blog
  label: Posts
  create: all
  match: "**/*"
  templates:
  - page
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - page
upload_dir: static/images/upload
public_path: "/images/upload"
front_matter_path: upload
use_front_matter_path: true
file_template: ":year:-:month:-:day:_:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.101.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public --environment
    staging --port 8080 --bind 0.0.0.0 --baseURL \
version: 0.101.0
